### ISSUE TITLE
Advice on leveraging Lumongo Storage with Hibernate Search

### ISSUE THREAD

**Issue by xyloman** [lumongo/lumongo#113]
A few days ago I put together a simple test of leveraging Lumongo Storage with Hibernate Search to make a more cloud friendly / container friendly approach to using hibernate search + lucene.  I found the lumongo-storage library was sufficient for these needs.  However, there is some piece of magic that is missing that I could use some assistance on.  Since we are just consuming the DistributedDirectory capability we notice that when a node writes to the index the updates are not seen on other running JVMs that are also pointed to the same mongo instance.  After restarting the JVMs updates to the index are then seen.  It appears that there is a cache in the mongo client or nosql file.  Assistance would be greatly appreciated.

**Comment by mdavis95** [comment]
This is an interesting use case but not one that is currently used inside Lumongo.

Inside Lumongo an index is made up of multiple Lumongo segments.  These Lumongo segments are lucene indexes like you are using via lumongo-storage. The segments are distributed across different servers.  These segments are never loaded by different servers at the same time but instead will fail between servers as needed.

I might be able to help you some with your use case if I know a few more details:

What is the nature of the multiple JVMs (are they mirrors, is it to scale)?
Are you writing with multiple nodes or is there one node that is the "master"?

**Comment by xyloman** [comment]
The multiple JVMs are mirrors.  We are coordinating writing through a leader election mechanic.  Not to get too winded but updates to the index are placed in a rabbitmq exchange that is only consumed by the one writer but many nodes can collect updates that need to be made for scale.  

Prior we were using a file system approach and then using a broadcast mechanic to update each JVMs copy of the data.   We are wanting to move to docker containers for this application so a lucene local file system is no longer a good idea.   

By the way thanks for the quick response.

**Comment by mdavis95** [comment]
So Lumongo does have a cache that is set via
```java
//The cache size in memory is approximately the block size (32k default) * the number of blocks
MongoDirectory.setMaxIndexBlocks(numberOfBlocks);
```
but this cache cannot be disabled.  However it is probably something you want to tune to avoid OOM errors and for performance (fetching each block from MongoDB is significantly slower than memory).

There is also a cache clearing mechanism which might be another piece of the puzzle:
```java
MongoFile.clearCache();
```

I think what you need to do is clear the cache and reopen the directory periodically or when you know there is an update (lumongo doesn't have a mechanism for this).  Not sure if that helps any but please let me know if there is anything else I can answer.

**Comment by xyloman** [comment]
Let me dig into this a little bit and we will see if we can make some progress.  Thanks for the feedback.

**Comment by mdavis95** [comment]
Any progress here?
