### ISSUE TITLE
Allow streaming results in query rest service for CSV

### ISSUE THREAD

**Issue by mdavis95** [lumongo/lumongo#151]

**Comment by mdavis95** [comment]
Batch mode needs to be used with an id sort if the index is changing.

**Comment by mdavis95** [comment]
id as part of the sort is fine as well
ex. sort title:asc,id:asc

**Comment by mdavis95** [comment]
query REST param batch=true&batchSize=500 

batch size defaults to 500 and batch is off by default

**Comment by payammeyer** [comment]
This isn't actually opening a streaming output, need to fix that.

**Comment by mdavis95** [comment]
@payammeyer is this fixed?

**Comment by payammeyer** [comment]
Yes, the commit is: ab4cd8d506e6f8c6b3f35d12c05a4c909ceb569b
