### ISSUE TITLE
the packaged util/protoc binary doesnt work on osx

### ISSUE THREAD

**Issue by conorroche** [lumongo/lumongo#33]
I wonder if it would be better to expect protoc to be on the path rather than pointing to the one in the util dir which isn't cross platform. On osx i changed lumongo-common/build.gradle to work around this

//String protocCommand = rootProject.file("util" + File.separator +  "protoc").toString();
String protocCommand = "protoc"

**Comment by mdavis95** [comment]
Using the protoc on the path on every os other than Linux
