### ISSUE TITLE
working dir variable in the bash scripts like clusteradmin.sh doesnt work on osx

### ISSUE THREAD

**Issue by conorroche** [lumongo/lumongo#34]
instead of this which for me doesnt work on osx 10.9.5

WORKING_DIR=$(dirname $(readlink -f ${BASH_SOURCE[0]}))

you could have the below which works on osx/linux

WORKING_DIR="${BASH_SOURCE[0]}";
if ([ -h "${WORKING_DIR}" ]) then
  while([ -h "${WORKING_DIR}" ]) do WORKING_DIR=`readlink "${WORKING_DIR}"`; done
fi
pushd . > /dev/null
cd `dirname ${WORKING_DIR}` > /dev/null
WORKING_DIR=`pwd`;
popd  > /dev/null

**Comment by mdavis95** [comment]
All scripts have been updated
