### ISSUE TITLE
Allow csv output in rest query service

### ISSUE THREAD

**Issue by mdavis95** [lumongo/lumongo#99]
&type=json will be default

&type=csv will export csv

&fl will specific which fields will be exported to the csv

&fl=title to include or &fl=-title to exclude from export

If a query is run and rows are returned export the documents and ignore any facets.  One facet is run and no rows are returned, return the facets.

**Comment by kirkbaker** [comment]
&type=csv doesn't escape commas in multi-valued fields leading to incorrect output

**Comment by payammeyer** [comment]
I've made a fix, attached is an example export.
[test.txt](https://github.com/lumongo/lumongo/files/484929/test.txt)

**Comment by payammeyer** [comment]
Also, the type parameter is no longer valid, it's now "format". An example request would be:

http://localhost:32192/query?index=indexName&q=*:*&fetch=true&rows=10&fl=id&fl=multiValueField&format=csv

**Comment by payammeyer** [comment]
e15fbadb830143fa95f74738e4dbc78450bf4043
